### PR TITLE
Hopeful update for 1.2.3.

### PR DESCRIPTION
**Pull request by ghost**
Please test this, then if it works accept the pull req. I tested it lightly, and it starts up, and no errors come up in my NetBeans.

### CODE REVIEW

**Comment by ghost** [comment]
Just with this, all .java files are now under /src/main/java/[packages]/[name].java and all .yml files are now under /src/main/resources/[name].yml

**Comment by matejdro** [comment]
Could you possibly change it so java files are back into /src?

**Comment by ghost** [comment]
Sorry, it's just that Netbeans only reads it if they're in src/main/java... Can you live with that? Or not? :P you could accept the req then move the files :)

**Comment by ghost** [comment]
I presume you use eclipse?

**Comment by ghost** [comment]
I also put up a link to my build of it on the dev.bukkit.org page... so... yeah... Please test and maybe submit it to the dev.bukkit.org page!

**Comment by matejdro** [comment]
Well, problem is that I cannot see changelog with that one. Thanks for update, I will rename stuff.

**Comment by ghost** [comment]
There is nothing changed, all I did was just change CraftServer to Server in 4 places. There were no additions, but you could put "Bug Fixes" into the changelog... /me shrugs :P

**Comment by matejdro** [comment]
Damn, I screwed something up and I cannot auto-merge it. Will do it tommorow.

**Comment by ghost** [comment]
Okey dokey! Hope to see it available soon. :)

YoshiGenius

```
YoshiCraft Minecraft Servers
Sydney, NSW, Australia
http://www.yoshicraft.tk
```

**Comment by matejdro** [comment]
Unfortunately I had no time to pull this in and I will be away for several days.

However, I have added you as Author to Jail bukkit dev page, so you can upload fix in the meantime.

**Comment by ghost** [comment]
That's a shame. I'll do my best in terms of fixes. :)

YoshiGenius

```
YoshiCraft Minecraft Servers
Sydney, NSW, Australia
http://www.yoshicraft.tk
```

**Pull request merged**
